feat: implement make with requirements.txt
WG-CC/transitiontoolkit-backend pull request #5
Opened 2024-04-18 22:33 UTC by NabbeunNabi

# Description
I installed a `Makefile` which has commands to run what developers need to run the files we are using right now. I would like someone on Mac to make sure the commands work on Mac and that they can run the `Makefile` commands as I tested them on Windows

# Closes issue(s)

Resolves #2 

# How to test
To test you want to go to my branch and try to run the following commands in this order

1.  `make venv` : This should install the venv on your local computer
2.  `make install`: This should install the requirements.txt
3.  `make run`: This should run the endpoint for `/` and you should see `Hello World`
4.  `make clean`: At the moment doesn't do anything noticeable
5.  `make freeze`: Should update the requirements.txt file if you add or change dependencies. Though at the moment for testing it won't change any as you aren't adding any

**THIS NEEDS TO BE TESTED BY SOMEONE ON A MAC TO MAKE SURE THE COMMAND `MAKE` IS WORKING PROPERLY ON THAT OS. I CODE ON A WINDOWS**

# Changes include
FastApi was added as a dependency. 

# Checklist

- [x] I have tested this code
- [x] I have updated the README

2024-04-19 00:05 UTC, Anissa3005 requested changes
Looks great ✨working with a make file for the first time can be bit challenging since it's less straightforward. 

- Some things we need to consider is, which version of python are we using?  We need to make sure that everyone is using the same version. So we need to implement that somewhere.
- In the `make` file, if I just would run a command without activated my venv that can cause trouble. So we need to think about how we can avoid that. Since when I did `make run` it didn't activated for me. So we can just mention it in the readme or we can add it in the make file. (we can pair on it if you need help)

2024-04-19 00:08 UTC, Anissa3005 commented on README.md
> + ### On Windows
Maybe we can also consider adding recommendations for VSCode extensions in our readme. Like extensions for Python, makefile,...

2024-04-21 19:10 UTC, NabbeunNabi commented on README.md
> + ### On Windows
I did update the Readme a bit

2024-04-24 04:36 UTC, hccleveland commented on README.md
> + ### On Windows
✅ This also works on Mac. Just the venv activation is outstanding.

2024-05-22 03:44 UTC, hccleveland requested changes
Just a few points of cleaning up. Sorry to miss these earlier.

2024-05-22 03:44 UTC, hccleveland commented on Makefile
> +	@echo "  run         to run the FastAPI server"
Should also change to `runserver`.

2024-05-22 03:44 UTC, hccleveland commented on Makefile
> +	@echo "  clean       to clean up the virtual environment"
Do we also want to add `freeze` to the list?

2024-05-22 03:44 UTC, hccleveland commented on README.md
> +3.  Run `make install`
Do we now want to specify what requires manual activation of the virtual environment and what is activated automatically?

2024-05-29 04:37 UTC, hccleveland approved these changes
LGTM. Tested locally on Mac.

2024-05-29 12:43 UTC, Anissa3005 approved these changes
LGTM

2024-05-29 12:43 UTC, merged